language: node_js
rvm:
  - "1.8.7"
node_js:
  - 0.4
  - 0.6
  - 0.7 # development version of 0.8, may be unstable
before_install:
  - npm install coffee-script
  - npm install mocha-phantomjs
script: make tests
install:
  - gem install jsduck
